[workspace]
resolver = "2"
members = [
    "drillx",
    "examples/*",
    "program"
]

[workspace.package]
version = "2.0.0-alpha"
edition = "2021"
license = "Apache-2.0"
homepage = "https://miraland.io/marsh"
documentation = "https://miraland.io/marsh"
repository = "https://github.com/miraland-labs/drillx"
readme = "./README.md"
keywords = ["solana", "crypto", "miraland", "mars", "marsh"]

[workspace.dependencies]
blake3 = "1.5"
bytemuck = { version  = "1.16", features = ["derive"] }
criterion = { version = "0.5", features = ["html_reports"] }
equix = "0.1.5"
solana-program = "^2"
solana-program-test = "^2"
solana-sdk = "^2"
strum = { version = "0.26.2", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3

[profile.bench]
lto = "fat"
codegen-units = 1
opt-level = 3

